### ISSUE TITLE
Different working dir when installing prevents initial unlock

### ISSUE THREAD

**Issue by evavh** [dvdsk/Book-safe#6]
When running the book-safe binary with a different working directory than the book-safe/ directory that the binary is in, the initial unlock doesn't work. This only happens if the install is run during locked times.

The unlock code looks in the wrong directory for the locked books, namely the working dir that the systemd timer uses, rather than the working dir where it was installed.

This could probably be fixed by changing the working directory for the initial lock run (when installing) to the same dir that is used in the systemd timer service.

**Comment by yara-blue** [comment]
we should probably just hard code it to `/home/root/Book-safe`. That takes away the option to determine the book-safe dir through the current working dir. However I do not think anyone does that.

As I do not think we have a significant user base a warning in the *Readme* combined with a major version increment should take care of the backwards incompatibility this introduces.
